milkypostman/powerline

powerline-separators.el

* when looking up background colors, pay attention to both face
inheritance and inverse-video, so we get the color that is actually
displayed as the background; and
* when using UTF-8 separators, ensure that `:inverse-video` is `nil` so
the separator colors don’t end up reversed.
This is related to sellout/emacs-color-theme-solarized#115 and fixes #22
(although #22 is already closed).

Improve background-color handling.

---

powerline-separators.el

See #87. The problem shows up in emacs 25, in which it seems that `cl-subseq`
changes in such a way to not accept a nil sequence. The chamfer separator was generating nil sequences because of the absence of a second-pattern or footer pattern for example. 
This change fixes the problem for me and should be backwards compatible. All it does is check for the existence of header, center, etc. before adding them to the list in `pl/pattern-defun`

FIX #87: Allow `pl/pattern-defun` to accept less patterns

---

powerline-themes.el
powerline.el

Modifying foreground of one section of the powerline had the annoying effect of also affecting other sections.
Thus I modified the code so that one can set faces for each part of the display independently, for more flexible customization:
* added new face mode-line-buffer-id-inactive
* explicitly set face to each section of the powerline.
Not really sure for powerline-center-evil-theme, as I am not a user of evil-mode.
I did not touch which-func-mode's face since a) it already has its own and b) I couldn't manage to modify it anyways.
If you want me to modify my PR please feel free to send feedback :)
Here is a screenshot of what I wanted to achieve with these modifications:
I also modified [theme monokai](https://github.com/oneKelvinSmith/monokai-emacs.git) to get this effect.

More flexible faces customization

---

powerline.el

powerline-vc: same vcs display in tty and gui emacs, using the UTF-8 'branch' char and the more compact and informative vc-mode variable

---

powerline.el

Added customize option to hide/show vcs glyph in GUI, with a default to 'hide'. Also removed extra space after glyph.

---

powerline.el

 Fixed missing mouse features of powerline-buffer-id while optimizing the entire function.

---

powerline-separators.el
powerline.el

Fixes #54.
Adds a custom option 'powerline-broken-image-srgb', which should be
set to 't' to enable the workaround. This is not needed on Emacs-mac
port, or when Apple RGB colors are used by setting
'ns-use-srgb-colorspace' to nil.

Fix broken sRGB colors on MacOS.

---

powerline.el

This commit adds an option to view the encoding of a file in
Powerline by taking the functionality from TheBB's Spaceline.
By adding something like 
`(powerline-encoding face2 'r)`
to your custom powerline theme either "unix", "dos", "mac" or
"utf-8" will display in your Powerline with the selected
face, hopefully addressing issue #112

Add encoding segment

---

powerline.el

Detect narrowing in the same way (buffer-narrowed-p) does.

Allow customizing the indicator showing a buffer is narrowed.

---

powerline.el

Since the last version the mode-line-buffer-identification variable is not used anymore, instead the buffer identification is always set to the current buffer name "%b".

Use mode-line-buffer-identification variable instead of %b

---

powerline-separators.el
powerline-themes.el
powerline.el

As you know, I use some custom elisp to inspect the permission statement or License header keyword in the "main library".
If that fails, I use the `licensee` tool to determine the license specified by the `LICENSE` (or similar) file. If that fails I use the Github API to detect to ask them what license they detected. They also use `licensee` for that purpose, but apparently they have changed its configuration because sometimes it works for them but not for me.
The oddest case is when Github displays the license for a repository on the webpage, but over the API it claims that it was not able to detect the license. That's what is happening here.
To avoid the failing blackbox, I am adding the permission statements to the library headers. Doing that is a good idea regardless of this issue …

Add permission statement to library headers

---

powerline.el

Fix https://github.com/milkypostman/powerline/issues/104.
Related issues/PRs:
- https://github.com/milkypostman/powerline/issues/120
- https://github.com/milkypostman/powerline/issues/104
- https://github.com/milkypostman/powerline/pull/134

Update the mode line when switching frames with window managers

---

powerline-separators.el
powerline.el

Why introduce an option when it can be done automatically? :P 
This color space problem only ever exists on the NS port, so I'm pretty sure this is safe.
References: #54 #141 
https://developer.apple.com/documentation/appkit/nsdisplaygamut/nsdisplaygamutsrgb?language=objc
https://en.wikipedia.org/wiki/Darwin_(operating_system)#Release_history

Set apple color space automatically

---

powerline-themes.el

The powerline-display-buffer-size and powerline-display-hud variables
currently only have effect on the default theme. This patch makes them
apply to the center and center-evil themes as well.

Use powerline-display-{buffer-size,hud} where appropriate

---

powerline.el

Per the official docs of select-window if you want to call a function every time a window is selected you should use buffer-list-update-hook. It automatically does The Right Thing, gets called only when necessary and you don't need to pay attention to norecord arguments.
The correction isn't theoretical either, advising select-window can lead to nasty feedback loops as in https://github.com/Alexander-Miller/treemacs/issues/369.

Use buffer-list-update-hook instead of advising select-window.

---

powerline.el

This is a fix to #176. 
The call to `powerline-hud` results in the same arguments being passed to `create-image` as in 26.3. The docs for `create-image` say:
> If the property ‘:scale’ is not given and the
> display has a high resolution (more exactly, when the average width of a
> character in the default font is more than 10 pixels), the image is
> automatically scaled up in proportion to the default font.
I don't know what changed for 27.1, but passing `:scale t` to `create-image` fixes the problem in 27.1 and doesn't seem to have any negative effect on 26.3.

Fix scaling for powerline-hud image

---

powerline.el

The official replacement is the after-focus-change-function used
here. It is working on my local copy.

The focus-in-hook and focus-out-hook are deprecated

---

powerline-separators.el

Fixes #176
Same thing as e15e77ab2e589bd73f9e90498747d77d042789ea but for separators.

fix scaling for separators

---

powerline-separators.el
powerline.el

t is no longer accepted as :scale argument for create-image, but using 1
has the same behavior as before.
Fixes #184.

Change :scale arugment from t to 1

---

powerline-separators.el

Emacs 28 has [enabled](https://github.com/emacs-mirror/emacs/commit/3a3226716b84c29c7eee9e19054ffe7618bd334c) SRGB support for images on the NS port, so converting from generic RGB to sRGB is no longer necessary. This fixes an issue where the separator images are off color on the NS port of emacs 28.

Disable powerline-image-apple-rgb on Emacs 28

---

powerline-separators.el

Replace the circular list in pl/pattern with a ring so the new and shiny JIT can compile powerline. Added some minor memory optimizations too.

Fix #187 replace circular list to enable native compilation

---

powerline-separators.el
powerline.el

This fixes some byte-compiler warnings on Emacs 28.
```
Compiling file /home/skangas/wip/emacs-packages/powerline/powerline.el at Mon Jan  3 03:54:46 2022
Entering directory ‘/home/skangas/wip/emacs-packages/powerline/’
powerline.el:142:1: Warning: custom-declare-variable
`powerline-gui-use-vcs-glyph' docstring wider than 80 characters
In pl/create-or-get-cache:
powerline.el:152:8: Warning: docstring wider than 80 characters
In powerline-desktop-save-delete-cache:
powerline.el:184:8: Warning: docstring wider than 80 characters
In pl/make-xpm:
powerline.el:262:8: Warning: docstring wider than 80 characters
In pl/percent-xpm:
powerline.el:297:8: Warning: docstring wider than 80 characters
In powerline-hud:
powerline.el:318:8: Warning: docstring wider than 80 characters
In powerline-raw: …
```

Fix byte-compiler warnings on Emacs 28

---

powerline.el

Hi!
I am investigating if we could add this package to [NonGNU ELPA](http://elpa.nongnu.org/) (see link), a new Emacs Lisp package archive that will be enabled by default in Emacs 28. This means that users of that version or later will be able to install this package without any configuration: they can just run `M-x list-packages` and install it out of the box. We hope that this will improve Emacs and help bring new users to this package and others.
The main difference between NonGNU ELPA and MELPA is that only stable versions of packages are released. A new release will be made automatically when you bump the "Version" commentary header in this repository, as I do in this commit. In the future, you can bump the package version (thereby releasing a new version) when you think it makes …

Bump version to 2.5 for NonGNU ELPA
